services:
  - type: web
    name: freshglobal-ecommerce
    env: node
    buildCommand: yarn install && yarn build
    startCommand: yarn global add serve && serve -s build
    staticPublishPath: ./build
